Repository Andrew-Dagher/SOEN-390, pull requests merged in 2025-03, with the labels that each got.

#129 Connect google calendar
  frontend/app/screens/calendar/CalendarScreen.jsx
  frontend/app/screens/login/LoginScreen.jsx
Labels: subtask

#139 [REFACTOR] Homescreen Improvements
  frontend/app/components/Homescreen/HomeHeader/HomeHeader.jsx
  frontend/app/screens/home/.HomeScreen.jsx.swp
  frontend/app/screens/home/HomeScreen.jsx
  frontend/package-lock.json
  frontend/package.json
Labels: refactor

#141 Feature/us 06.1 connect google calendar
  frontend/__tests__/CalendarHelper-test.jsx
  frontend/__tests__/CalendarScreen-test.jsx
  frontend/__tests__/GoToClassButton-test.jsx
  frontend/__tests__/NotificationObserver-test.jsx
  frontend/app/components/Calendar/GoToClassButton.jsx
  frontend/app/components/Calendar/GoToLoginButton.jsx
  frontend/app/components/InAppNotification.js
  frontend/app/components/navigation/Map.jsx
  frontend/app/screens/calendar/CalendarHelper.js
  frontend/app/screens/calendar/CalendarScreen.jsx
  frontend/app/screens/calendar/CalendarScreenStyles.js
  frontend/app/screens/calendar/EventObserver.js
  frontend/app/screens/calendar/NotificationObserver.js
  frontend/app/screens/login/LoginScreen.jsx
  frontend/app/screens/navigation/NavigationScreen.jsx
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
Labels: User Story, subtask, enhancements

#127 [FEATURE] Show shuttle bus locations on map (US 106)
  frontend/__tests__/BottomNavBar.test.jsx
  frontend/__tests__/BusService.test.jsx
  frontend/__tests__/CalendarScreen.test.jsx
  frontend/__tests__/HomeHeader.test.jsx
  frontend/__tests__/LoginScreen.test.jsx
  frontend/__tests__/MapBusService.test.jsx
  frontend/__tests__/NavigationScreen.test.jsx
  frontend/__tests__/SettingsScreen.test.jsx
  frontend/app/App.js
  frontend/app/components/navigation/Map.jsx
  frontend/app/services/BusService.js
  frontend/assets/shuttle-bus-map.png
  frontend/package-lock.json
  frontend/package.json
Labels: enhancements

#145 Feature/us 6.4 generate directions to next class
  frontend/__tests__/CalendarScreen.test.jsx
  frontend/__tests__/NextClassButton.test.jsx
  frontend/__tests__/__snapshots__/CalendarScreen.test.jsx.snap
  frontend/app/components/Calendar/NextClassButton.js
  frontend/app/screens/calendar/CalendarScreen.jsx
  frontend/app/screens/calendar/CalendarScreenStyles.js
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: subtask
